##第三章 ES2015新语法详解

####3.10 Promise

Promise的最大目的在于让异步代码变得井然有序，而不是无限的嵌套和回调。
比如我们需要在浏览器中访问一个以JSON作为返回格式的第三方API，在数据下载完成后进行JSON解码，通过Promise来包装异步流程可以使代码变得非常整洁：

fetch('http://example.com/api/users/top')
  .then(res => res.json())
  .then(data => {
    //...
  })
  .catch(err => console.error(err)) // 处理错误

Promise在设计上具有原子性，即只有3种状态：等待（Pending）、成功（Fulfilled）、失败（Rejected）。这让我们在调用支持Promise的异步方法时，逻辑变得非常简单，这在大规模的软件工程开发中具有良好的健壮性。

阮老师的书：
Promise的两个特点：
（1）对象的状态不受外界影响。只有异步操作的结果可以决定当前是哪一种状态。Promise的意思是“承诺”，即表示其他手段无法改变。
（2）一旦状态改变，就不会再变，任何时候都可以得到这个结果。只能从pending变为Resolved（又称Fulfilled）或从pending变为Rejected。一旦发生，不会再变，且再去访问，也会立即得到这个结果。

#####3.10.1 基本语法
######3.10.1.1 创建Promise对象

要给一个函数赋予Promise的能力，就要先创建一个Promise对象，并将其作为函数值返回。Promise构造函数要求传入一个函数，并带有resolve和reject参数。这是两个用于结束Promise等待的函数，对应的状态分别为成功和失败。

//Syntax:
// new Promise((resolve, reject) => statements) : Promise
function asyncMethod(...args) {
  return new Promise((resolve, reject) => {
  //...
  })
}

将新创建的Promise对象作为异步方法的返回值，所有的状态就可以使用它所提供的方法进行控制了。

######3.10.1.2 进行异步操作

创建了Promise对象后，就可以进行异步操作，并通过resolve(value) 和 reject(reason) 方法控制Promise的原子状态。
【阮老师：
resolve函数的作用是，将Promise对象的状态从“未完成”变为“成功”
reject函数的作用是，将Promise对象状态从“未完成”变为“失败”】
1. resolve(value)方法控制的是当前Promise对象是否进入成功状态，一旦执行该方法并传入有且只有一个返回值，Promise便会从等待状态（Pending）进入成功状态（Fulfilled），Promise也不会再接受任何状态的改变。
2. reject(reason) 方法控制的是当前Promise对象是否进入失败阶段，与resolve方法相同，一旦进入失败阶段就无法再改变。

//Syntax:
// resolve(value)
// reject(reason)

new Promise((resolve, reject) => {
  api.call('fetch-data',(err,data) => {
    if(err) return reject(err);
    resolve(data);
  })
})

其中在Promise的首层函数作用域中一旦出现throw语句，Promise对象便会直接进入失败状态，并以throw语句的抛出值作为错误值进行错误处理。

(new Promise(function() {
  throw new Error('test')
}))
  .catch(err => console.error(err))

但是相对的return语句却并不会使Promise对象进入成功状态，而会使Promise停留在等待状态。所以在Promise对象的执行器（executor）内需要谨慎使用return语句来控制代码流程。

######3.10.1.3 处理Promise的状态

Promise有两个用于处理Promise对象状态变化的方法：
1.promise.then(onFulfilled[,onRejected])
处理Promise对象的成功状态并接收返回值，也可以处理失败状态并处理失败的原因（可选）
2.promise.catch(onRejected)
处理Promise对象的失败状态并处理失败的原因

这两个方法都会返回一个Promise对象，会形成一个Promise对象链，呈流水线（Pipeline）的模式作业。

//Syntax: promise.then(onFulfilled).catch(onRejected) : Promise
asyncMethod()
  .then((...args) => args /* ... */)
  .catch(err => console.error(err))

Promise链式处理被默认实现，即.then(...)或.catch(...)会处理在onFulfilled和onRejected中返回的值
【阮老师：
then方法的第一个参数是Promise对象状态变为Resolved时调用，第二是是状态变为Rejected时调用（可选）。这两个函数都接受Promise对象那个传出的值作为参数】

阮老师的例子：

function timeout(ms) {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, ms, 'done');
  });
}
timeout(100).then((value) => {
  console.log(value);
});

上面代码中，timeout 方法返回一个Promise实例，表示一段时间后才会发生的结果。过了指定的时间（ms参数）以后，Promise实例的状态变为Resolved，就会触发then方法绑定的回调函数。

再来一个Promise新建后会立即执行的例子：


let promise = new Promise(function(resolve, reject) {
  console.log('Promise');
  resolve();
});
promise.then(function() {
  console.log('Resolved.');
});

console.log('Hi');

//Promise
//Hi
//Resolved.

上述代码中，Promise新建后立即执行，所以首先输出的是“Promise”。然后，then方法指定的回调函数，将在当前脚本所有同步任务执行完才会执行，所以“Resolved”最后输出。
